### ISSUE TITLE
python 3.11 install support

### ISSUE THREAD

**Issue by jhao0117** [timeplus-io/proton-python-driver#24]
when pip install proton-driver on python 3.11 env, error:
```
  Running setup.py install for proton-driver ... error
  error: subprocess-exited-with-error
```

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by jovezhong** [comment]
I also failed to use 0.2.8 python driver with 3.11.5 python

> -311/proton_driver/columns/largeint.o
      proton_driver/columns/largeint.c:209:12: fatal error: 'longintrepr.h' file not found
        #include "longintrepr.h"
                 ^~~~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]

>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for proton-driver
> Failed to build proton-driver
> ERROR: Could not build wheels for proton-driver, which is required to install pyproject.toml-based projects
> python3 --version
> Python 3.11.5

**Comment by jovezhong** [comment]
Reopen this ticket since new package is not pushed @leo-cai-timeplus , @qijun-niu-timeplus , @jhao0117 , @gangtao 

source py311-env/bin/activate
pip install proton-driver

proton_driver/columns/largeint.o
      proton_driver/columns/largeint.c:209:12: fatal error: 'longintrepr.h' file not found
        #include "longintrepr.h"
                 ^~~~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for proton-driver
Failed to build proton-driver
ERROR: Could not build wheels for proton-driver, which is required to install pyproject.toml-based projects

**Comment by jovezhong** [comment]
proton-driver is not updated. timeplus-proton-driver should be removed.

I reopen this ticket

 @qijun-niu-timeplus

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by qijun-niu-timeplus** [comment]
I've updated the proton-driver. Close this issue.
